export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export const SET_SORT_PENDING = 'SET_SORT_PENDING';
export const SET_SORT_SUCCESS = 'SET_SORT_SUCCESS';

export const SEARCH_DATA_REQUEST = 'SEARCH_DATA_REQUEST';
export const SEARCH_DATA_SUCCESS = 'SEARCH_DATA_SUCCESS';
export const SEARCH_POPUP = 'SEARCH_POPUP';
export const TOGGLE_STATE = 'TOGGLE_STATE';
export const SET_ENUM_FILTER_PENDING = 'SET_ENUM_FILTER_PENDING';
export const SET_ENUM_FILTER_SUCCESS = 'SET_ENUM_FILTER_SUCCESS';
export const GLOBAL_SEARCH_PENDING = 'GLOBAL_SEARCH_PENDING';
export const GLOBAL_SEARCH_SUCCESS = 'GLOBAL_SEARCH_SUCCESS';

export const SET_VIRTUALIZATION = 'SET_VIRTUALIZATION';
export const SET_SELECT_ROW = 'SET_SELECT_ROW';
export const DELETE_ROWS = 'DELETE_ROWS';
export const SET_HIDDEN_COLUMNS = 'SET_HIDDEN_COLUMNS';
